apiVersion: v1
kind: Secret
metadata:
  name: billing-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-billingdb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.billingdb.auth.username }}
  DB_PASSWORD: {{ .Values.billingdb.auth.password }}
  DB_DBNAME: {{ .Values.billingdb.auth.database }}
  DB_PORT: "5432"