apiVersion: v1
kind: Service
metadata:
  name: billing-app
  labels:
    app: billing-app
spec:
  selector:
    app: billing-app
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.billing.port}}
  type: ClusterIP
