apiVersion: v1
kind: ConfigMap
metadata:
  name: myorder-app-config
data:
  APP_PORT: "{{ .Values.myorder.port}}"
  APP_SERVICE_NAME: "my_order_service"
  KAFKA_HOST: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local"
  KAFKA_PORT: "9092"
  KAFKA_PAYMENT_STATUS_TOPIC: "payment-status"
  KAFKA_ORDER_CREATED_TOPIC: "order-created"
