apiVersion: v1
kind: Secret
metadata:
  name: myorder-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-myorderdb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.myorderdb.auth.username }}
  DB_PASSWORD: {{ .Values.myorderdb.auth.password }}
  DB_DBNAME: {{ .Values.myorderdb.auth.database }}
  DB_PORT: "5432"