apiVersion: v1
kind: Service
metadata:
  name: myorder-app
  labels:
    app: myorder-app
spec:
  selector:
    app: myorder-app
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.myorder.port}}
  type: ClusterIP
